### ISSUE TITLE
Failure message not being delivered

### ISSUE THREAD

**Issue by its02003** [kuleuven/jenkins-mattermost-plugin#14]
I've added "Notify Build Start", "Notify Aborted", "Notify Failure" and "Notify Success" options to the plugin for a job. All the notifications seem to work fine except the "Notify Failure" which isn't showing up. I have yet to check the logs since I don't have access to them at the moment, but I was wondering if this is something you've seen before?

**Comment by jovandeginste** [comment]
The failure notifications work in my setup (sadly, my code is sometimes broken ;-)). I can confirm on Monday when I'm back at work - maybe something broke with the last updates?

**Comment by its02003** [comment]
Ok cool, in the meantime I'll try to see if its something obvious in the logs. This might also be a catalyst for me to finally pick up some Java code for the first time since college :)

**Comment by jovandeginste** [comment]
Sure thing! Debugging is very easy if you have Linux, a recent Java and maven: just clone the repo and run `mvn package`. First run will take a while (downloading the internet), results in a hpi in `./target` which you copy to your plugins folder on your Jenkins server (deleting the jpi there). Then start editing the files and repeat.

**Comment by its02003** [comment]
So got access to the logs, wasn't as much help as I'd hoped:

When I do something in the build like supply invalid credentials to my GitLab repo, the failure posts to MM

When my Ansible playbook fails to deploy, the build fails but the API call never triggers. This includes any entries in the Jenkins logs... The only one I see is:

INFO: Posting: to **MM_channel_name**@http://**MM_server_address**/hooks/**endpoint_ID**: **jenkins_project_name** - #47 Started by user **me** [Open](http://**jenkins_server**:8080/job/**jenkins_project_name**/47/) (danger)

**Comment by its02003** [comment]
Any thoughts on this one? I'm not seeing anything in the primary Jenkins logs that lend themselves to explanations for the missing MM message, are there other logs anywhere?

**Comment by jovandeginste** [comment]
Is Ansible run through a Jenkins plugin for Ansible, or via shell commands?

**Comment by its02003** [comment]
A plugin... It actually fails and causes the build to fail, but doesn't trigger the "Build Failed" message in this MM plugin.

**Comment by its02003** [comment]
Here is the Jenkins build command line output:

ERROR: Ansible playbook execution failed
Performing Post build task...
Post build task logic removed
END OF POST BUILD TASK  : 0
Finished: FAILURE

**Comment by jovandeginste** [comment]
Long shot, and I have no idea how to diagnose this further, but maybe the Ansible plugins fails in a wrong way....

**Comment by jovandeginste** [comment]
Ok, I know of a way: can you add a different type of post build action?

**Comment by its02003** [comment]
The problem I've found so far with the Post Build Actions is that they don't seem to have access to the Jenkins Environment variables, which reduces the usefulness of the generated error messages.

Can you give me an idea of what your plugin is triggering on for the failure? I'll track down the Ansible plugin and see if that is indeed the problem. Just want to make sure I understand what you trigger off so I can compare.

**Comment by jovandeginste** [comment]
I'm not sure I understand you correctly; Jenkins triggers some methods in my plugin. It's just part of the API...

There is a post build action called "Record fingerprints of files to track usage" that you could try just to debug -- does this action get triggered after failure or not?

**Comment by its02003** [comment]
Sorry, I meant post build task in my previous comment, the plugin for tasks doesn't seem to support the environment variables.

I'll try the fingerprint action to see if that helps.

**Comment by jovandeginste** [comment]
Any update?

**Comment by silk-bahamut** [comment]
Hello,
I have the same problem.
I have a build with some Site Monitor (https://wiki.jenkins-ci.org/display/JENKINS/SiteMonitor+Plugin) which are only after build actions

One of the monitor fails and then the notification on failure is not sent.

**Comment by jovandeginste** [comment]
@silk-bahamut did you find anything useful (in this thread)?

**Comment by silk-bahamut** [comment]
@jovandeginste  no really, but as much as I remember I did not get it to work
