### ISSUE TITLE
Support for direct message channels

### ISSUE THREAD

**Issue by alexjrussell** [kuleuven/jenkins-mattermost-plugin#19]
Hello,

Thank you for creating this extremely useful plugin, we use it extensively in my department.  One small problem we have with it, however, is that we can't upgrade from version 2.0.2 because direct message channels no longer work.  The problem comes from the fact that direct message channel names are in the format @dmchannel and this is not compatible witth the plugin logic where you can specify user@channel.

In our Mattermost set-up, we have a user called jenkins that owns the webhooks and this means that if you specify @username as the Mattermost channel, the user will get a direct message from the jenkins user.  This is useful because users are more likely to notice direct messages.

Anyway, I have attached a patch that I made to the code on the master branch that I have recently tried in a test jenkins installation.  I would be very grateful if you would consider adding this or something simlilar to a future release.

Many thanks

[mmplugin.patch.txt](https://github.com/jovandeginste/jenkins-mattermost-plugin/files/1081258/mmplugin.patch.txt)

**Comment by jovandeginste** [comment]
@alexjrussell out of curiosity, why did you not make a pull request?

I'll look into this Monday or Tuesday. Thanks in advance!

**Comment by alexjrussell** [comment]
@jovandeginste I couldn't work out how to create a pull request at first but I managed to do it now :)  Hope that helps.  Many thanks

**Comment by jovandeginste** [comment]
Great work, thanks in advance! Will look into it on Monday. Are you running master branch with your PR now?

**Comment by jovandeginste** [comment]
Should be released shortly; for the impatient: https://github.com/jenkinsci/mattermost-plugin/releases

**Comment by alexjrussell** [comment]
Awesome!  Thanks for adding this change so quickly!

**Comment by jovandeginste** [comment]
When you provide a clean patch, it's easy to work fast.
