### ISSUE TITLE
Support direct message channels with spaces

### ISSUE THREAD

**Issue by MarioSteinitz** [kuleuven/jenkins-mattermost-plugin#21]
I just played around with the new direct message channels features. Yet lowercase author (bot) names with dashes do not look very pretty in our Mattermost channels. Therefore, I was wondering whether we could remove the space from the roomIds splitting and trim the channel / author names after they have been extracted from the room IDs. This would allow for author names with spaces...

**Comment by jovandeginste** [comment]
We could do this. You don't happen to know how to announce/handle "breaking changes" in Jenkins plugins? I know there are possibilities but a few quick googles didn't reveal much. I'll look further into later if you happen to know :-)

**Comment by MarioSteinitz** [comment]
Honestly, I don't. It just happened, that I had to alter some standard plugins a little here and there to addressing issues with our corporate IT infrastructure. Never created an own plugin myself / did the Jenkins publishing/upgrading parts.

**Comment by jovandeginste** [comment]
This should be solved with v2.4.0
