### ISSUE TITLE
DM to the buildbreakers

### ISSUE THREAD

**Issue by rpost** [kuleuven/jenkins-mattermost-plugin#28]
As in title: I'd like to have possibility to send direct messages to the developers who caused build to fail (as in mailer plugin for example).

**Comment by jovandeginste** [comment]
That should be possible if you use Jenkinsfile; you can specify `@username` as a channel. You need to map the developper handle to his Mattermost username, of course.

**Comment by jovandeginste** [comment]
I will close this for inactivity
