### ISSUE TITLE
Error posting to Mattermost : hostname in certificate did not match

### ISSUE THREAD

**Issue by christophelec** [kuleuven/jenkins-mattermost-plugin#30]
Hello,

While testing the connection between my Jenkins and Mattermost instances, I get the following error :
```
Error posting to Mattermost
javax.net.ssl.SSLException: hostname in certificate didn't match: <mattermostinstance> != </platform on which mattermost is running>
```

My mattermost instance is on a platform using [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) for HTTPS, and the name provided in the certificate is the one of the platform : I suspect the plugin does not handle SNI.

I found multiple reports of similar issues with other Jenkins plugin :
https://issues.jenkins-ci.org/browse/JENKINS-37030
https://issues.jenkins-ci.org/browse/JENKINS-40903

I'm not extremely skilled in Java, but I can try to provide a fix if this issue is not being worked on already.

Regards,

**Comment by jovandeginste** [comment]
Thanks for reporting this, and for the pointers. I'm by no means skilled in Java either, so feel free to give it a shot! Otherwise I will contact other people who are skilled, and who may be able to assist me...

**Comment by covert8** [comment]
Updated http client lib to currentday lib in dev branch. Should support SNI.

**Comment by covert8** [comment]
Changes have been merged to master. Waiting for RC to clear
