### ISSUE TITLE
Cannot change settings (i.e. endpoint) in "classic" Jenkins

### ISSUE THREAD

**Issue by Unpublished** [kuleuven/jenkins-mattermost-plugin#31]
Happens since https://github.com/kuleuven/jenkins-mattermost-plugin/commit/f8a52af1da1b64e9ad3eb51b5b84f66d7e139219

Workaround: Downgrade to 2.5.2.

**Comment by jovandeginste** [comment]
@ewelinawilkosz @ndeloof any thoughts?

**Comment by ewelinawilkosz** [comment]
that was a very trivial change, didn't expect to cause any trouble... will have a look

**Comment by ewelinawilkosz** [comment]
@jovandeginste is endpoint the only field you have trouble with?

**Comment by jovandeginste** [comment]
@Unpublished can you provide an answer? I'll see if I can reproduce, meanwhile

**Comment by jovandeginste** [comment]
@ewelinawilkosz I can reproduce: changing any item in the configuration is not persisted
Talking about all of:
* endpoint
* channel
* Icon to use
* Build Server URL

**Comment by ewelinawilkosz** [comment]
thanks for checking so fast, I'll try to fix today afternoon, will keep you updated

**Comment by ewelinawilkosz** [comment]
fix on the way, PR with comment: https://github.com/jenkinsci/mattermost-plugin/pull/8

**Comment by jovandeginste** [comment]
@Unpublished v2.6.1 is released; can you provide feedback when you get a chance?

**Comment by Unpublished** [comment]
The issue is fixed, thank you both!

**Comment by ewelinawilkosz** [comment]
good to hear, sorry for the mess!

**Comment by jovandeginste** [comment]
@Unpublished thanks for reporting and feedback!
@ewelinawilkosz I consider this a small issue, not a mess... Thanks for your contribution (again) and for your swift fix!
