### ISSUE TITLE
Mattermost dedicated proxy settings

### ISSUE THREAD

**Issue by bartos** [kuleuven/jenkins-mattermost-plugin#34]
Would it be possible to add mattermost dedicated proxy settings?
We have a mattermost instance in the internet, but whole CI/CD is located in corporate network.
We can access this mattermost instance with setting up proxy in Jenkins, but that settings affects other things in Jenkins also. 

Separate proxy settings in the mattermost-plugin section would do the job nicely, without having to reinvent the wheel and preparing custom solutions.

Regards,
b.

**Comment by mazerty** [comment]
it would be really handy for us as well

environment variables seem to work but it requires the dns to resolve the mattermost server hostname, which is NOT required since it should be the proxy who resolve the names
we are stuck here :(

**Comment by bartos** [comment]
@mazerty I've created a pull request. 
Please test if you can.

**Comment by mazerty** [comment]
hi !
i'm really sorry but i don't have access to this jenkins anymore so i can't test it
besides, we went around this by using the http rest plugin
hope you'll find someone else to help you test this :)
