### ISSUE TITLE
Plugin does not support multiple no-proxy hosts

### ISSUE THREAD

**Issue by djh82** [kuleuven/jenkins-mattermost-plugin#40]
Plugin seems to access ProxyConfiguration.noProxyHosts directly and then attempts to convert glob -> regex.

If it used ProxyConfiguration.getNoProxyHostPatterns() then it would be able to handle multiple hosts and avoid the need to try and convert globs to regexes.

**Comment by covert8** [comment]
Hi @davidhart82 thanks for the suggestion.

v3.0.2 is now building and will be available shortly.
