### ISSUE TITLE
Research vulnerability log4j plugin and fix is needed

### ISSUE THREAD

**Issue by fdebrabander** [kuleuven/jenkins-mattermost-plugin#47]
Plugin uses 'log4j-over-slf4j' which might be vulnerable to https://logging.apache.org/log4j/2.x/security.html

Research is needed to determine if this plugin is vulnerable, if so the plugin needs a security fix.

**Comment by fdebrabander** [comment]
Looks like only version 2.x is vulnerable and this plugin uses older version.

**Comment by jovandeginste** [comment]
The irony...
