### ISSUE TITLE
Sending a message to a different team is not working

### ISSUE THREAD

**Issue by Gabson1** [kuleuven/jenkins-mattermost-plugin#48]
Hi, I am trying to get this plugin working for my team.
The plugin works as expected in team#1, however does not work at all for team#2 (although they both exist under the same organization (server). I've tried setting the endpoint to match the MM-URL of team#2, but I am still getting an error.

___
"Mattermost send pipeline step configured values from global config - connector: false, icon: true, channel: false, color: falseERROR: Mattermost notification failed. See Jenkins logs for details."
___

Note that:
- I am not the one who set this plugin up (somebody from team#1 did)
- if I want to look into the main Jenkins logs, I'd have to request that from the Jenkins server maintainers.

I don't know if this is an issue, me using the plugin incorrectly or just a matter of adjusting the global configuration for the jenkins-mattermost plugin

**Comment by covert8** [comment]
Hi, i have some questions

- Does the webhook have permissions to post in the channel of the 2nd team?
- Could you nonetheless take a look at the jenkins logs or have them search by someone else?
