### ISSUE TITLE
Jenkins Pipeline

### ISSUE THREAD

**Issue by Muzamri** [kuleuven/jenkins-mattermost-plugin#8]
Hi,

How do I get this to work with pipelines (if it's possible) ? I can't seem to find the docs for this.

For example, slack-plugin has this:
`slackSend color: 'good', message: 'Message from Jenkins Pipeline'`

TIA

**Comment by jovandeginste** [comment]
It appears that the Slack plugin has code for this: https://github.com/jenkinsci/slack-plugin/search?utf8=%E2%9C%93&q=slackSend

When I have more time available, I will try to rebase the plugin and add their changes ...

**Comment by eirikwang** [comment]
Hi. 
I started migrating latest slack code into master: 
https://github.com/eirikwang/jenkins-mattermost-plugin

let me know if you want a pull-request.

**Comment by jovandeginste** [comment]
@eirikwang Hi, great! Are you running the migrated code?

**Comment by eirikwang** [comment]
@jovandeginste verified it works with the pipeline plugin on latest jenkins.  Will test against regular jobs with post action tomorrow.

**Comment by jovandeginste** [comment]
@eirikwang thanks!

**Comment by jovandeginste** [comment]
There was a problem with the `url` in the `pom.xml`; I hope that this is the reason the plugin is "not available" at this time ... I published a new version with the fixed `pom.xml`...

**Comment by jovandeginste** [comment]
I'm now running it myself in production, it works as expected. Basic example:

``` groovy
node() {
    stage (name: 'Show firewall diff') {
        checkout scm
        sh "gem install bundler --no-ri --no-rdoc && bundle install"
        sh "./change_firewall -n"
        mattermostSend endpoint: 'redacted', channel: 'jenkins', color: 'warning', message: 'New firewall waiting for confirmation'
    }
    input message: "Firewall changes are ok ?"
    stage (name: 'Apply change') {
        sh "./change_firewall -y"
        mattermostSend endpoint: 'redacted', channel: 'jenkins', color: 'good', message: 'New firewall configuration was applied'
    }
}
```
